version: "3.8"
services:
  web:
    build: .
    command: sh -c "/wait && npm run start:prod"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=1
    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
    ports:
      - "3000:3000"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
